# TensorFlow基础

In [1]:
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.layers as layers

physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)
#需安装tensorflow-gpu版本可运行成功

AssertionError: Not enough GPU hardware devices available

## 数据类型

### 数值类型

标量在 TensorFlow 是如何创建的

In [2]:
# python 语言方式创建标量
a = 1.2 
# TF 方式创建标量
aa = tf.constant(1.2)

type(a), type(aa), tf.is_tensor(aa),aa.ndim

(float, tensorflow.python.framework.ops.EagerTensor, True, 0)

如果要使用 TensorFlow 提供的功能函数， 须通过 TensorFlow 规定的方式去创建张量，而不能使用 Python 语言的标准变量创建方式。

In [3]:
x = tf.constant([1,2.,3.3])
# 打印 TF 张量的相关信息                
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [4]:
# 将 TF 张量的数据导出为 numpy 数组格式
x.numpy() 

array([1. , 2. , 3.3], dtype=float32)

与标量不同，向量的定义须通过 List 容器传给 tf.constant()函数。

创建一个元素的向量：

In [5]:
# 创建一个元素的向量
a = tf.constant([1.2]) 
a, a.shape,a.ndim

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]),
 1)

创建 3 个元素的向量：

In [6]:
 # 创建 3 个元素的向量
a = tf.constant([1,2, 3.])
a, a.shape,a.ndim

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]),
 1)

定义矩阵

In [7]:
# 创建 2 行 2 列的矩阵
a = tf.constant([[1,2],[3,4]]) 
a, a.shape,a.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 TensorShape([2, 2]),
 2)

三维张量可以定义为：

In [8]:
# 创建 3 维张量
tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]]) 

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

### 字符串类型

通过传入字符串对象即可创建字符串类型的张量

In [9]:
# 创建字符串
a = tf.constant('Hello, Deep Learning.') 
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, Deep Learning.'>

在 tf.strings 模块中，提供了常见的字符串类型的工具函数，如小写化 lower()、 拼接
join()、 长度 length()、 切分 split()等。

In [10]:
# 小写化字符串
tf.strings.lower(a) 

<tf.Tensor: shape=(), dtype=string, numpy=b'hello, deep learning.'>

### 布尔类型
布尔类型的张量只需要传入 Python 语言的布尔类型数据，转换成 TensorFlow 内部布尔型即可。

In [11]:
# 创建布尔类型标量
tf.constant(True) 

<tf.Tensor: shape=(), dtype=bool, numpy=True>

创建布尔类型的向量

In [12]:
 # 创建布尔类型向量
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

需要注意的是， TensorFlow 的布尔类型和 Python 语言的布尔类型并不等价，不能通用

In [13]:
# 创建 TF 布尔张量
a = tf.constant(True) 
# TF 布尔类型张量与 python 布尔类型比较
print(a is True)
# 仅数值比较
a == True 

False


<tf.Tensor: shape=(), dtype=bool, numpy=True>

## 数值精度

在创建张量时，可以指定张量的保存精度

In [14]:
# 创建指定精度的张量
tf.constant(123456789, dtype=tf.int16)#overflow,get wrong result

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [15]:
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=123456789>

对于浮点数， 高精度的张量可以表示更精准的数据，例如采用 tf.float32 精度保存π时，实际保存的数据为 3.1415927

In [16]:
import numpy as np
# 从 numpy 中导入 pi 常量
np.pi 
# 32 位
tf.constant(np.pi, dtype=tf.float32) 

<tf.Tensor: shape=(), dtype=float32, numpy=3.1415927>

如果采用 tf.float64 精度保存π，则能获得更高的精度

In [17]:
tf.constant(np.pi, dtype=tf.float64) # 64 位

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

### 读取精度

通过访问张量的 dtype 成员属性可以判断张量的保存精度

In [18]:
a = tf.constant(np.pi, dtype=tf.float16)

# 读取原有张量的数值精度
print('before:',a.dtype) 
# 如果精度不符合要求，则进行转换
if a.dtype != tf.float32: 
    # tf.cast 函数可以完成精度转换
    a = tf.cast(a,tf.float32) 
# 打印转换后的精度
print('after :',a.dtype) 

before: <dtype: 'float16'>
after : <dtype: 'float32'>


### 类型转换
系统的每个模块使用的数据类型、 数值精度可能各不相同， 对于不符合要求的张量的类型及精度， 需要通过 tf.cast 函数进行转换

In [19]:
# 创建 tf.float16 低精度张量
a = tf.constant(np.pi, dtype=tf.float16) 
# 转换为高精度张量
tf.cast(a, tf.double) 

<tf.Tensor: shape=(), dtype=float64, numpy=3.140625>

进行类型转换时，需要保证转换操作的合法性， 例如将高精度的张量转换为低精度的张量时，可能发生数据溢出隐患：

In [20]:
a = tf.constant(123456789, dtype=tf.int32)
# 转换为低精度整型
tf.cast(a, tf.int16) 

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

布尔类型与整型之间相互转换也是合法的， 是比较常见的操作

In [21]:
a = tf.constant([True, False])
# 布尔类型转整型
tf.cast(a, tf.int32) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0])>

一般默认 0 表示 False， 1 表示 True，在 TensorFlow 中，将非 0 数字都视为 True，

In [22]:
a = tf.constant([-1, 0, 1, 2])
# 整型转布尔类型
tf.cast(a, tf.bool) 

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

## 待优化张量

TensorFlow 增加了一种专门的数据类型来支持梯度信息的记录： tf.Variable。 tf.Variable 类型在普通的张量类型基础上添加了 name， trainable 等属性来支持计算图的构建。

In [23]:
# 创建 TF 张量
a = tf.constant([-1, 0, 1, 2]) 
# 转换为 Variable 类型
aa = tf.Variable(a) 
# Variable 类型张量的属性
aa.name, aa.trainable 

('Variable:0', True)

name 属性用于命名计算图中的变量，这套命名体系是 TensorFlow 内部维护的， 一般不需要用户关注 name 属性；   
trainable属性表征当前张量是否需要被优化，创建 Variable 对象时是默认启用优化标志，可以设置trainable=False 来设置张量不需要优化。

In [24]:
# 直接创建 Variable 张量
tf.Variable([[1,2],[3,4]]) 

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

待优化张量可视为普通张量的特殊类型，普通张量其实也可以通过 GradientTape.watch()方法临时加入跟踪梯度信息的列表，从而支持自动求导功能

## 创建张量

### 从数组、列表对象创建

通过 tf.convert_to_tensor 函数可以创建新 Tensor，并将保存在 Python List 对象或者Numpy Array 对象中的数据导入到新 Tensor 中。

In [25]:
# 从列表创建张量
tf.convert_to_tensor([1,2.]) 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [26]:
# 从数组中创建张量
tf.convert_to_tensor(np.array([[1,2.],[3,4]])) 

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

### 创建全0或全1张量
tf.zeros(shape）,tf.ones(shape)

In [27]:
# 创建全 0，全 1 的标量
tf.zeros([]),tf.ones([]) 

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [28]:
# 创建全 0，全 1 的向量
tf.zeros([1]),tf.ones([1]) 

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

创建全 0 的矩阵

In [29]:
# 创建全 0 矩阵，指定 shape 为 2 行 2 列
tf.zeros([2,2]) 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

创建全 1 的矩阵

In [30]:
# 创建全 1 矩阵，指定 shape 为 3 行 2 列
tf.ones([3,2]) 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

通过 tf.zeros_like, tf.ones_like 可以方便地新建与某个张量 shape 一致， 且内容为全 0 或全 1 的张量。

In [31]:
# 创建一个矩阵
a = tf.ones([2,3]) 
# 创建一个与 a 形状相同，但是全 0 的新矩阵
tf.zeros_like(a) 

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

创建与张量A形状一样的全 1 张量

In [32]:
# 创建一个矩阵
a = tf.zeros([3,2]) 
# 创建一个与 a 形状相同，但是全 1 的新矩阵
tf.ones_like(a) 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

### 创建自定义数值张量

通过 tf.fill(shape, value)可以创建全为自定义数值 value 的张量，形状由 shape 参数指定。

In [33]:
# 创建-1 的标量
tf.fill([], -1) 

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [34]:
# 创建-1 的向量
tf.fill([1], -1) 

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([-1])>

In [35]:
# 创建 2 行 2 列，元素全为 99 的矩阵
tf.fill([2,2], 99) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]])>

### 创建已知分布的张量

通过 tf.random.normal(shape, mean=0.0, stddev=1.0,dtype=tf.float32)可以创建形状为 shape，均值为mean，标准差为 stddev 的正态分布$\mathcal{N}(mean, stddev^2)$。

In [36]:
# 创建标准正态分布的张量
tf.random.normal([2,2]) 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.12005481, -0.89149904],
       [-0.10116489,  0.7433044 ]], dtype=float32)>

In [37]:
# 创建均值为 1，标准差为 2 的正态分布的张量
tf.random.normal([2,2], mean=1,stddev=2) 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.9810698 , -2.9681606 ],
       [ 0.11106831, -2.2183657 ]], dtype=float32)>

通过 tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)可以创建采样自[minval, maxval)区间的均匀分布的张量

In [38]:
# 创建采样自[0,1)均匀分布的矩阵,如果是浮点数则最大值默认为1
tf.random.uniform([3,2]) 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.36782038, 0.43967593],
       [0.95087206, 0.84788215],
       [0.67067635, 0.046839  ]], dtype=float32)>

In [39]:
# 创建采样自[0,10)均匀分布的矩阵
tf.random.uniform([2,2],maxval=10) 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6.83151  , 2.3206902],
       [1.1785054, 3.4216368]], dtype=float32)>

如果需要均匀采样整形类型的数据，必须指定采样区间的最大值 maxval 参数，同时指定数据类型为 tf.int*型

In [40]:
# 创建采样自[0,100)均匀分布的整型矩阵
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[64, 41],
       [69, 12]])>

### 创建序列

tf.range(limit, delta=1)可以创建[0, limit)之间，步长为 delta 的整型序列，不包含 limit 本身。

In [41]:
# 0~10，不包含 10
tf.range(10) 

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [42]:
# 创建 0~10，步长为 2 的整形序列
tf.range(10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [43]:
tf.range(1,10,delta=2) # 1~10

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

## 张量的典型应用

### 标量

In [44]:
# 随机模拟网络输出
out = tf.random.uniform([4,10]) 
# 随机构造样本真实标签
y = tf.constant([2,3,2,0]) 
# one-hot 编码
y = tf.one_hot(y, depth=10) 
# 计算每个样本的 MSE
loss = tf.keras.losses.mse(y, out) 
# 平均 MSE,loss 应是标量
loss = tf.reduce_mean(loss) 
print(loss)

tf.Tensor(0.37382483, shape=(), dtype=float32)


### 向量

考虑 2 个输出节点的网络层， 我们创建长度为 2 的偏置向量b，并累加在每个输出节点上：

In [45]:
# z=wx,模拟获得激活函数的输入 z
z = tf.random.normal([4,2])
# 创建偏置向量
b = tf.zeros([2])
# 累加上偏置向量
z = z + b 
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.714706  ,  0.05763658],
       [ 0.44503176,  1.1185707 ],
       [-0.96824694,  2.871083  ],
       [ 1.9381356 , -0.96515054]], dtype=float32)>

创建输入节点数为 4，输出节点数为 3 的线性层网络，那么它的偏置向量 b 的长度应为 3

In [46]:
# 创建一层 Wx+b，输出节点为 3
fc = tf.keras.layers.Dense(3) 
# 通过 build 函数创建 W,b 张量，输入节点为 4
fc.build(input_shape=(1,4))
# 查看偏置向量
fc.bias 

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

### 矩阵

In [47]:
# 2 个样本，特征长度为 4 的张量
x = tf.random.normal([2,4]) 
# 定义 W 张量
w = tf.ones([4,3])
# 定义 b 张量
b = tf.zeros([3]) 
# X@W+b 运算
o = x@w+b 
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.485795 , 1.485795 , 1.485795 ],
       [1.4204538, 1.4204538, 1.4204538]], dtype=float32)>

In [48]:
# 定义全连接层的输出节点为 3
fc = tf.keras.layers.Dense(3) 
# 定义全连接层的输入节点为 4
fc.build(input_shape=(2,4)) 
print(fc.get_weights())
print(fc.weights)
# 查看权值矩阵 W
fc.kernel 

[array([[ 0.0315935 ,  0.16546237, -0.90166557],
       [ 0.58333564,  0.13615656, -0.38872004],
       [ 0.52373314, -0.034154  , -0.5695597 ],
       [-0.6321295 , -0.01819497, -0.54688823]], dtype=float32), array([0., 0., 0.], dtype=float32)]
[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.0315935 ,  0.16546237, -0.90166557],
       [ 0.58333564,  0.13615656, -0.38872004],
       [ 0.52373314, -0.034154  , -0.5695597 ],
       [-0.6321295 , -0.01819497, -0.54688823]], dtype=float32)>, <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]


<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.0315935 ,  0.16546237, -0.90166557],
       [ 0.58333564,  0.13615656, -0.38872004],
       [ 0.52373314, -0.034154  , -0.5695597 ],
       [-0.6321295 , -0.01819497, -0.54688823]], dtype=float32)>

### 三维张量

In [54]:
# 自动加载 IMDB 电影评价数据集
(x_train,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=10000)#将数据限定为前10000个最常出现的单词，不经常出现的单词被抛弃
# 将句子填充、截断为等长 80 个单词的句子
x_train = keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)#maxlen：None或整数，为序列的最大长度。大于此长度的将被截断，小于此长度的序列将在后面填0.
x_train.shape

(25000, 80)

可以看到 x_train 张量的 shape 为[25000,80]，其中 25000 表示句子个数， 80 表示每个句子共 80 个单词，每个单词使用数字编码方式表示。

我们通过 layers.Embedding 层将数字编码的单词转换为长度为 100 个词向量：

In [55]:
# 创建词向量 Embedding 层类
embedding = tf.keras.layers.Embedding(10000, 100) #10000个单词，每个单词转换成长度为100的向量
# 将数字编码的单词转换为词向量
out = embedding(x_train)
out.shape

TensorShape([25000, 80, 100])

可以看到，经过 Embedding 层编码后，句子张量的 shape 变为[25000,80,100]，其中 100 表示每个单词编码为长度是 100 的向量。

### 四维张量

In [56]:
# 创建 32x32 的彩色图片输入，个数为 4
x = tf.random.normal([4,32,32,3])
# 创建卷积神经网络
layer = layers.Conv2D(16, kernel_size=3)#[3,3,3]这样的卷积核有16个，因此经过卷积层后，会得到4个16通道30*30的矩阵。
# 前向计算
out = layer(x)
# 输出大小
out.shape

TensorShape([4, 30, 30, 16])

In [57]:
# 访问卷积核张量
layer.kernel.shape 

TensorShape([3, 3, 3, 16])

## 索引与切片
### 索引

In [58]:
# 创建4维张量
x = tf.random.normal([4,32,32,3]) 

In [59]:
# 取第 1 张图片的数据
x[0]

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 0.56132954,  1.0240716 , -0.695265  ],
        [ 0.30553484, -0.9748528 , -0.3334454 ],
        [-2.0479376 , -0.91174793, -0.45997626],
        ...,
        [-0.5992921 , -0.4015634 , -0.48222786],
        [-0.3929014 , -1.6305777 , -0.8734571 ],
        [ 0.34042674,  1.1267968 ,  0.41962907]],

       [[-0.80559283,  0.4040911 , -0.84643364],
        [ 1.2207829 ,  0.5733357 ,  0.27591863],
        [-0.42436305, -1.8920491 ,  1.9671875 ],
        ...,
        [ 0.78289473,  0.6905323 , -0.43980932],
        [ 0.5259124 ,  0.74883085,  0.45092174],
        [-1.0944672 , -1.0788081 ,  0.6706025 ]],

       [[ 1.4613035 ,  0.13465251,  1.8708674 ],
        [-1.2515901 , -1.2327672 , -0.73722744],
        [ 1.1814649 , -0.20128182, -0.50636333],
        ...,
        [-1.6747677 ,  0.64008003,  0.36425805],
        [-1.4294685 ,  0.75576574, -0.6863536 ],
        [-0.72690636, -0.29798338,  0.8318101 ]],

       ...,

       

In [60]:
# 取第 1 张图片的第 2 行
x[0][1]

<tf.Tensor: shape=(32, 3), dtype=float32, numpy=
array([[-0.80559283,  0.4040911 , -0.84643364],
       [ 1.2207829 ,  0.5733357 ,  0.27591863],
       [-0.42436305, -1.8920491 ,  1.9671875 ],
       [ 1.0676625 , -0.14453442, -0.44366768],
       [-0.11034721,  0.68550944, -1.8465581 ],
       [ 1.7585673 ,  1.1833974 ,  1.3173681 ],
       [-0.22177438,  0.98509234, -0.5816487 ],
       [-0.59577924,  1.6136149 ,  0.67506593],
       [-0.1011188 ,  0.3346612 ,  1.2177188 ],
       [ 0.8624578 , -0.8500602 , -0.07364078],
       [ 0.9429823 ,  0.2710342 , -0.06769212],
       [-0.1815276 ,  0.7321146 , -0.75649935],
       [-1.085658  ,  0.25998333,  0.178231  ],
       [-0.35312602, -0.35323015,  0.302885  ],
       [-0.0489605 , -0.3486175 ,  0.71964854],
       [-0.44715032, -0.45575297,  0.73565453],
       [-0.20593886, -0.49678773,  0.68824625],
       [-0.7551396 ,  0.8197193 , -0.14241251],
       [ 0.02974381, -1.2329326 ,  0.9171778 ],
       [-2.165373  , -1.6385571 ,  0.16

In [61]:
# 取第 1 张图片，第 2 行，第 3 列的数据
x[0][1][2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.42436305, -1.8920491 ,  1.9671875 ], dtype=float32)>

In [62]:
# 取第 3 张图片，第 2 行，第 1 列的像素， B 通道(第 2 个通道)颜色强度值
x[2][1][0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.6706184>

In [63]:
# 取第 2 张图片，第 10 行，第 3 列的数据
x[1,9,2]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.10191809, 1.3791635 , 0.06647474], dtype=float32)>

### 切片

In [64]:
# 读取第 2,3 张图片
x[1:3]

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 1.6741270e+00, -5.7527298e-01,  1.6495043e-01],
         [-3.7657741e-01,  7.2483367e-01, -8.5025537e-01],
         [ 2.0016260e+00,  2.0015779e+00, -1.2772887e+00],
         ...,
         [-7.8604048e-01,  2.5375748e-01,  2.7030128e-01],
         [ 3.0131266e-01, -1.0002141e+00, -2.2603220e-01],
         [-3.1529716e-01, -1.3276199e+00, -1.2411907e+00]],

        [[-6.3182062e-01,  4.2279711e-01,  1.4948167e+00],
         [-2.3454182e+00, -4.6802530e-01,  2.3029145e-02],
         [ 2.8627288e-01,  2.3491980e-01,  1.5992329e-01],
         ...,
         [ 1.8941858e-01,  1.4146873e+00, -3.5354163e-02],
         [ 1.3018798e+00, -1.0040305e+00, -6.4206243e-01],
         [ 2.6368988e-01,  9.1697156e-01,  1.9523838e-01]],

        [[ 4.4351327e-01,  2.4326675e-01,  5.1995605e-01],
         [-4.3405473e-01,  2.2621698e+00, -1.1509615e-01],
         [ 2.0542336e-01, -1.1978177e+00,  2.3717134e-01],
         ...,
         [-6.

In [65]:
# 读取第一张图片
x[0,::] 

<tf.Tensor: shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 0.56132954,  1.0240716 , -0.695265  ],
        [ 0.30553484, -0.9748528 , -0.3334454 ],
        [-2.0479376 , -0.91174793, -0.45997626],
        ...,
        [-0.5992921 , -0.4015634 , -0.48222786],
        [-0.3929014 , -1.6305777 , -0.8734571 ],
        [ 0.34042674,  1.1267968 ,  0.41962907]],

       [[-0.80559283,  0.4040911 , -0.84643364],
        [ 1.2207829 ,  0.5733357 ,  0.27591863],
        [-0.42436305, -1.8920491 ,  1.9671875 ],
        ...,
        [ 0.78289473,  0.6905323 , -0.43980932],
        [ 0.5259124 ,  0.74883085,  0.45092174],
        [-1.0944672 , -1.0788081 ,  0.6706025 ]],

       [[ 1.4613035 ,  0.13465251,  1.8708674 ],
        [-1.2515901 , -1.2327672 , -0.73722744],
        [ 1.1814649 , -0.20128182, -0.50636333],
        ...,
        [-1.6747677 ,  0.64008003,  0.36425805],
        [-1.4294685 ,  0.75576574, -0.6863536 ],
        [-0.72690636, -0.29798338,  0.8318101 ]],

       ...,

       

In [66]:
x[:,0:28:2,0:28:2,:]

<tf.Tensor: shape=(4, 14, 14, 3), dtype=float32, numpy=
array([[[[ 0.56132954,  1.0240716 , -0.695265  ],
         [-2.0479376 , -0.91174793, -0.45997626],
         [-0.47912043, -0.40068835,  0.67203045],
         ...,
         [-1.2807636 , -0.3384167 ,  2.157176  ],
         [ 0.10868204,  0.3552552 , -0.5827466 ],
         [-0.07533111, -0.8372107 ,  0.30599824]],

        [[ 1.4613035 ,  0.13465251,  1.8708674 ],
         [ 1.1814649 , -0.20128182, -0.50636333],
         [ 1.0807685 , -0.70296943, -0.08981103],
         ...,
         [-0.5888172 ,  0.508318  , -1.682396  ],
         [ 2.311887  , -0.46670192,  1.5736936 ],
         [-2.2390554 ,  0.6785103 ,  0.09167726]],

        [[-0.01689445,  0.24428028,  1.398478  ],
         [ 2.0079107 ,  1.6125416 , -1.2239937 ],
         [ 0.93338406,  1.1310692 ,  0.93183786],
         ...,
         [-0.33533534, -0.16484046,  1.0545899 ],
         [ 0.1928536 ,  0.55326027,  0.3039886 ],
         [-0.6081011 , -0.2990299 , -1.2675229 ]

In [67]:
# 考虑一个 0~9 的简单序列向量， 逆序取到第 1 号元素，不包含第 1 号
# 创建 0~9 向量
x = tf.range(9) 
# 从 8 取到 0，逆序，不包含 0
x[8:0:-1] 

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1])>

In [68]:
# 逆序全部元素
x[::-1] 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0])>

In [69]:
# 逆序间隔采样
x[::-2] 

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0])>

读取每张图片的所有通道，其中行按着逆序隔行采样，列按着逆序隔行采样

In [70]:
x = tf.random.normal([4,32,32,3])
# 行、列逆序间隔采样
x[0,::-2,::-2] 

<tf.Tensor: shape=(16, 16, 3), dtype=float32, numpy=
array([[[ 2.36737058e-01, -2.14821172e+00,  2.35090065e+00],
        [-2.98216492e-01,  1.09962976e+00, -5.33090055e-01],
        [-5.62160492e-01,  3.45662571e-02, -2.13674402e+00],
        [-3.51955444e-01,  2.16031879e-01, -1.47814798e+00],
        [ 3.96228909e-01, -9.49557543e-01, -1.03401554e+00],
        [ 3.40410438e-03, -1.45476341e+00, -3.34389776e-01],
        [-3.93793821e-01,  4.53851640e-01,  6.61554158e-01],
        [-1.57868195e+00, -7.66618431e-01,  2.04635143e+00],
        [ 2.28901625e+00, -1.58218086e+00, -2.47457087e-01],
        [ 3.90340537e-01, -6.00661278e-01, -1.06475365e+00],
        [ 2.46542946e-01, -3.41126651e-01,  1.03897929e+00],
        [ 1.83093226e+00, -2.25892410e-01,  9.83753800e-01],
        [ 8.73290777e-01,  9.53373194e-01,  1.25863373e+00],
        [ 2.28961587e+00,  6.36347115e-01, -1.04803884e+00],
        [ 8.48179936e-01, -2.01501995e-01,  4.20074522e-01],
        [-1.82771933e+00,  2.101

In [71]:
# 取 G 通道数据
x[:,:,:,1] 

<tf.Tensor: shape=(4, 32, 32), dtype=float32, numpy=
array([[[-1.03862536e+00,  5.19991159e-01,  1.25529945e-01, ...,
         -9.59230810e-02,  1.40601480e+00,  1.22627997e+00],
        [ 8.54619563e-01, -1.17459095e+00, -1.30192423e+00, ...,
         -8.62191916e-01,  8.58335868e-02, -2.00877525e-02],
        [-4.09677207e-01,  1.18854189e+00, -5.99503458e-01, ...,
          1.89400390e-01, -1.04004525e-01,  5.51722765e-01],
        ...,
        [-1.36972561e-01,  8.95012617e-01, -9.30583358e-01, ...,
          3.12717944e-01,  6.24758720e-01,  9.21691716e-01],
        [-3.54396284e-01,  3.31374168e-01, -2.40086615e-01, ...,
          8.23955983e-02, -1.28802729e+00,  4.46416438e-01],
        [ 6.99917436e-01,  2.10180413e-03,  2.49295104e-02, ...,
          1.09962976e+00,  3.32235843e-01, -2.14821172e+00]],

       [[-8.14973474e-01, -8.42658997e-01, -3.89963716e-01, ...,
          5.08580923e-01, -1.46357095e+00,  5.91082692e-01],
        [-9.37178373e-01,  1.61391467e-01,  1.0618

In [72]:
# 读取第 1~2 张图片的 G/B 通道数据
# 高宽维度全部采集
x[0:2,...,1:] 

<tf.Tensor: shape=(2, 32, 32, 2), dtype=float32, numpy=
array([[[[-1.03862536e+00,  4.24130529e-01],
         [ 5.19991159e-01, -1.17353475e+00],
         [ 1.25529945e-01, -6.25412583e-01],
         ...,
         [-9.59230810e-02,  1.10581493e+00],
         [ 1.40601480e+00,  4.11194801e-01],
         [ 1.22627997e+00,  3.75761539e-01]],

        [[ 8.54619563e-01,  1.15949237e+00],
         [-1.17459095e+00,  5.79580545e-01],
         [-1.30192423e+00, -1.64396286e-01],
         ...,
         [-8.62191916e-01,  9.57023203e-01],
         [ 8.58335868e-02, -1.23484445e+00],
         [-2.00877525e-02, -4.74127412e-01]],

        [[-4.09677207e-01, -3.09708178e-01],
         [ 1.18854189e+00, -2.31672740e+00],
         [-5.99503458e-01, -1.13266063e+00],
         ...,
         [ 1.89400390e-01, -4.39132839e-01],
         [-1.04004525e-01,  6.25984132e-01],
         [ 5.51722765e-01, -6.41442537e-01]],

        ...,

        [[-1.36972561e-01, -8.05640221e-01],
         [ 8.95012617e-01, 

In [73]:
# 读取最后 2 张图片
# 高、宽、通道维度全部采集，等价于 x[2:]
x[2:,...] 

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 4.91080642e-01, -1.03492570e+00, -5.36334515e-01],
         [ 1.05459392e+00,  3.62774551e-01, -2.38023788e-01],
         [ 6.49792671e-01,  9.14300382e-01, -5.84140956e-01],
         ...,
         [-1.37091368e-01,  2.36883378e+00, -7.67858088e-01],
         [-1.26511109e+00, -1.87651545e-01, -9.14575696e-01],
         [ 1.07445002e+00,  5.84657133e-01,  3.38971883e-01]],

        [[-9.30824399e-01,  6.78434610e-01, -4.69526350e-01],
         [-1.31433582e+00,  1.07234442e+00, -2.33317733e-01],
         [ 1.18276536e+00,  6.58936024e-01,  4.25413698e-01],
         ...,
         [ 1.66926491e+00, -1.86725545e+00, -1.15011621e+00],
         [ 7.58674741e-01,  9.82444584e-01, -1.18680835e+00],
         [-5.15812933e-01, -7.41998792e-01,  9.86822724e-01]],

        [[-4.37134862e-01, -3.85336220e-01,  8.98110807e-01],
         [-7.85729766e-01,  2.48472720e-01, -1.98602748e+00],
         [ 6.20537363e-02, -1.04293518e-01, 

In [74]:
# 读取 R/G 通道数据
# 所有样本，所有高、宽的前 2 个通道
x[...,:2] 

<tf.Tensor: shape=(4, 32, 32, 2), dtype=float32, numpy=
array([[[[-1.49692941e+00, -1.03862536e+00],
         [-6.72032982e-02,  5.19991159e-01],
         [-8.76666129e-01,  1.25529945e-01],
         ...,
         [ 1.77476394e+00, -9.59230810e-02],
         [-4.76283699e-01,  1.40601480e+00],
         [-6.69692338e-01,  1.22627997e+00]],

        [[-9.92194638e-02,  8.54619563e-01],
         [-4.35981423e-01, -1.17459095e+00],
         [ 1.45168245e+00, -1.30192423e+00],
         ...,
         [ 2.21172750e-01, -8.62191916e-01],
         [-1.08279586e+00,  8.58335868e-02],
         [-1.05969198e-01, -2.00877525e-02]],

        [[-1.19502890e+00, -4.09677207e-01],
         [ 2.97446936e-01,  1.18854189e+00],
         [-4.40631330e-01, -5.99503458e-01],
         ...,
         [-1.47128332e+00,  1.89400390e-01],
         [-5.04857302e-01, -1.04004525e-01],
         [-6.76708937e-01,  5.51722765e-01]],

        ...,

        [[-1.05548286e+00, -1.36972561e-01],
         [-1.63488770e+00, 

## 维度变换

### 改变视图

我们通过 tf.range()模拟生成一个向量数据，并通过 tf.reshape 视图改变函数产生不同的视图

In [75]:
# 生成向量
x = tf.range(96) 
# 改变 x 的视图，获得 4D 张量，存储并未改变
x = tf.reshape(x,[2,4,4,3]) 
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

In [76]:
# 获取张量的维度数和形状列表
x.ndim,x.shape 

(4, TensorShape([2, 4, 4, 3]))

In [77]:
tf.reshape(x,[-1])

<tf.Tensor: shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])>

通过 tf.reshape(x, new_shape)，可以将张量的视图任意地合法改变

In [78]:
tf.reshape(x,[2,-1])

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

In [79]:
 tf.reshape(x,[2,4,12])

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]])>

In [80]:
tf.reshape(x,[2,-1,3])

<tf.Tensor: shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]])>

### 增、删维度

In [81]:
# 产生矩阵
x = tf.random.uniform([28,28],maxval=10,dtype=tf.int32)
x

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[8, 3, 5, 1, 8, 0, 2, 2, 0, 9, 5, 1, 2, 4, 3, 3, 4, 2, 4, 6, 1, 9,
        4, 9, 1, 8, 3, 6],
       [8, 1, 0, 3, 1, 7, 2, 9, 8, 3, 0, 4, 4, 5, 9, 2, 0, 1, 6, 3, 5, 0,
        4, 6, 5, 2, 2, 0],
       [3, 1, 1, 0, 9, 7, 9, 8, 0, 5, 1, 9, 1, 1, 2, 3, 6, 1, 9, 9, 9, 2,
        4, 2, 4, 4, 1, 0],
       [3, 9, 2, 5, 7, 6, 3, 1, 6, 5, 3, 9, 7, 0, 8, 8, 4, 8, 2, 3, 8, 2,
        9, 0, 3, 8, 3, 9],
       [6, 7, 4, 8, 2, 7, 4, 9, 8, 1, 8, 8, 0, 9, 8, 1, 8, 2, 2, 7, 4, 5,
        3, 4, 8, 0, 2, 2],
       [9, 8, 6, 9, 0, 3, 2, 6, 5, 8, 8, 6, 7, 8, 6, 8, 3, 3, 3, 3, 3, 8,
        5, 7, 5, 5, 7, 2],
       [4, 6, 9, 0, 3, 0, 5, 9, 3, 5, 0, 9, 6, 4, 1, 3, 1, 3, 1, 6, 9, 2,
        2, 4, 7, 7, 0, 3],
       [8, 7, 6, 8, 8, 6, 9, 5, 8, 7, 4, 1, 8, 2, 9, 6, 2, 2, 0, 5, 1, 2,
        9, 3, 4, 1, 2, 2],
       [5, 8, 9, 6, 1, 2, 0, 3, 7, 1, 9, 2, 0, 5, 1, 0, 9, 6, 9, 5, 6, 9,
        0, 7, 1, 0, 7, 0],
       [2, 3, 9, 2, 8, 3, 4, 6, 9, 7, 6, 9,

通过 tf.expand_dims(x, axis)可在指定的 axis 轴前可以插入一个新的维度

In [82]:
# axis=2 表示宽维度后面的一个维度
x = tf.expand_dims(x,axis=2) 
x

<tf.Tensor: shape=(28, 28, 1), dtype=int32, numpy=
array([[[8],
        [3],
        [5],
        [1],
        [8],
        [0],
        [2],
        [2],
        [0],
        [9],
        [5],
        [1],
        [2],
        [4],
        [3],
        [3],
        [4],
        [2],
        [4],
        [6],
        [1],
        [9],
        [4],
        [9],
        [1],
        [8],
        [3],
        [6]],

       [[8],
        [1],
        [0],
        [3],
        [1],
        [7],
        [2],
        [9],
        [8],
        [3],
        [0],
        [4],
        [4],
        [5],
        [9],
        [2],
        [0],
        [1],
        [6],
        [3],
        [5],
        [0],
        [4],
        [6],
        [5],
        [2],
        [2],
        [0]],

       [[3],
        [1],
        [1],
        [0],
        [9],
        [7],
        [9],
        [8],
        [0],
        [5],
        [1],
        [9],
        [1],
        [1],
        [2],
        [3],
        [

In [83]:
x = tf.expand_dims(x,axis=0) # 高维度之前插入新维度
x

<tf.Tensor: shape=(1, 28, 28, 1), dtype=int32, numpy=
array([[[[8],
         [3],
         [5],
         [1],
         [8],
         [0],
         [2],
         [2],
         [0],
         [9],
         [5],
         [1],
         [2],
         [4],
         [3],
         [3],
         [4],
         [2],
         [4],
         [6],
         [1],
         [9],
         [4],
         [9],
         [1],
         [8],
         [3],
         [6]],

        [[8],
         [1],
         [0],
         [3],
         [1],
         [7],
         [2],
         [9],
         [8],
         [3],
         [0],
         [4],
         [4],
         [5],
         [9],
         [2],
         [0],
         [1],
         [6],
         [3],
         [5],
         [0],
         [4],
         [6],
         [5],
         [2],
         [2],
         [0]],

        [[3],
         [1],
         [1],
         [0],
         [9],
         [7],
         [9],
         [8],
         [0],
         [5],
         [1],
    

In [84]:
x = tf.squeeze(x, axis=0) # 删除图片数量维度
x

<tf.Tensor: shape=(28, 28, 1), dtype=int32, numpy=
array([[[8],
        [3],
        [5],
        [1],
        [8],
        [0],
        [2],
        [2],
        [0],
        [9],
        [5],
        [1],
        [2],
        [4],
        [3],
        [3],
        [4],
        [2],
        [4],
        [6],
        [1],
        [9],
        [4],
        [9],
        [1],
        [8],
        [3],
        [6]],

       [[8],
        [1],
        [0],
        [3],
        [1],
        [7],
        [2],
        [9],
        [8],
        [3],
        [0],
        [4],
        [4],
        [5],
        [9],
        [2],
        [0],
        [1],
        [6],
        [3],
        [5],
        [0],
        [4],
        [6],
        [5],
        [2],
        [2],
        [0]],

       [[3],
        [1],
        [1],
        [0],
        [9],
        [7],
        [9],
        [8],
        [0],
        [5],
        [1],
        [9],
        [1],
        [1],
        [2],
        [3],
        [

In [85]:
x = tf.random.uniform([1,28,28,1],maxval=10,dtype=tf.int32)
tf.squeeze(x) # 如果不指定维度参数 axis，那么它会默认删除所有长度为 1 的维度

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[8, 4, 8, 1, 7, 1, 6, 0, 8, 1, 8, 6, 0, 3, 6, 1, 2, 3, 8, 6, 8, 9,
        5, 7, 9, 5, 9, 5],
       [6, 9, 1, 0, 8, 5, 9, 6, 2, 4, 4, 3, 2, 2, 5, 6, 4, 5, 7, 4, 1, 9,
        2, 5, 9, 6, 6, 2],
       [8, 6, 4, 4, 2, 0, 1, 1, 8, 8, 6, 6, 1, 2, 8, 8, 4, 8, 6, 0, 5, 3,
        2, 2, 8, 5, 7, 7],
       [3, 2, 9, 8, 4, 4, 5, 0, 4, 0, 9, 8, 8, 1, 5, 5, 7, 9, 4, 5, 8, 1,
        5, 5, 1, 3, 7, 9],
       [1, 6, 6, 5, 6, 6, 9, 6, 8, 9, 4, 6, 5, 4, 4, 5, 3, 6, 2, 0, 7, 4,
        4, 3, 1, 4, 4, 6],
       [0, 5, 7, 3, 8, 4, 5, 7, 2, 8, 5, 9, 6, 4, 4, 0, 7, 7, 7, 7, 4, 7,
        4, 7, 8, 5, 7, 3],
       [1, 1, 3, 4, 9, 7, 9, 3, 2, 5, 5, 7, 6, 5, 5, 4, 9, 5, 9, 8, 2, 2,
        9, 3, 9, 5, 4, 9],
       [9, 3, 4, 0, 5, 6, 8, 4, 3, 9, 2, 4, 9, 4, 3, 0, 3, 0, 5, 6, 1, 8,
        0, 5, 2, 8, 7, 9],
       [9, 6, 1, 3, 6, 5, 2, 0, 1, 1, 5, 5, 8, 5, 8, 5, 1, 3, 4, 1, 3, 5,
        2, 1, 3, 3, 2, 6],
       [4, 3, 2, 2, 4, 2, 7, 4, 1, 7, 9, 0,

### 交换维度
如在 TensorFlow 中，图片张量的默认存储格式是通道后行格式：[𝑏,ℎ,w,𝑐]，但是部分库的图片格式是通道先行格式：[𝑏,𝑐,ℎ,w]，因此需要完成[𝑏,ℎ,w,𝑐]到[𝑏,𝑐,ℎ,w]维度交换运算，此时若简单的使用改变视图函数 reshape，则新视图的存储方式需要改变，因此使用改变视图函数是不合法的。

In [86]:
x = tf.random.normal([2,32,32,3])
# 交换维度
tf.transpose(x,perm=[0,3,1,2]) #参数 perm表示新维度的顺序 List,为index列表

<tf.Tensor: shape=(2, 3, 32, 32), dtype=float32, numpy=
array([[[[-0.34757972,  0.79794836,  0.63790697, ...,  2.5396845 ,
           0.5400969 ,  0.15017168],
         [ 0.31631023, -1.6190698 , -0.8243391 , ...,  0.1494381 ,
          -0.54608226,  0.89199495],
         [ 0.5917818 , -0.0499099 ,  0.8103298 , ..., -1.4206301 ,
           1.189264  ,  0.94316244],
         ...,
         [-0.26709497,  2.1040733 ,  0.653659  , ...,  0.63518053,
           0.94392496,  0.20440184],
         [ 0.16445805, -0.19657946, -0.88474   , ..., -0.2844142 ,
          -0.15086284,  1.9761076 ],
         [-0.26328388,  0.21004994,  0.57012916, ..., -0.8957526 ,
          -0.82474273,  0.714669  ]],

        [[-0.53390265,  1.5007316 , -0.34257025, ...,  0.20722434,
           1.6602516 ,  1.0587937 ],
         [ 0.94386476,  1.1435946 ,  2.0225983 , ..., -0.22161172,
           0.8015205 , -0.36406106],
         [-0.49592325,  0.7310962 , -0.3486807 , ..., -0.65505785,
          -0.64068514,  0.555

### 复制数据
当通过增加维度操作插入新维度后，可能希望在**新的维度上**面复制若干份数据，满足后续算法的格式要求。

In [87]:
# 创建向量 b
b = tf.constant([1,2]) 
# 插入新维度，变成矩阵
b = tf.expand_dims(b, axis=0) 
b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

In [88]:
# 样本维度上复制一份
b = tf.tile(b, multiples=[3,2]) #multiples 分别指定了每个维度上面的复制倍数，对应位置为 1 表明不复制，为 2 表明新长度为原来长度的2 倍，即数据复制一份，以此类推
b

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]])>

In [89]:
x = tf.range(4)
# 创建 2 行 2 列矩阵
x=tf.reshape(x,[2,2]) 
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

In [90]:
# 列维度复制一份
x = tf.tile(x,multiples=[1,2]) 
x

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]])>

In [91]:
# 行维度复制一份
x = tf.tile(x,multiples=[2,1]) 
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])>

In [92]:
x = tf.tile(x,multiples=[2,2]) 
x

<tf.Tensor: shape=(8, 8), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3]])>

## Broadcasting
Broadcasting 称为广播机制(或自动扩展机制)，它是一种轻量级的张量复制手段，在逻辑上扩展张量数据的形状，但是只会在需要时才会执行实际存储复制操作。对于大部分场景，Broadcasting 机制都能通过优化手段避免实际复制数据而完成逻辑运算，从而相对于tf.tile 函数，减少了大量计算代价。

In [93]:
# 创建矩阵
A = tf.random.normal([32,1]) 
# 扩展为 4D 张量
tf.broadcast_to(A, [2,32,32,3]) #[32,1]->[32,3]->[32,32,3]->[2,32,32,3]

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[ 0.21102734,  0.21102734,  0.21102734],
         [ 0.42117536,  0.42117536,  0.42117536],
         [ 0.93851733,  0.93851733,  0.93851733],
         ...,
         [-1.3705354 , -1.3705354 , -1.3705354 ],
         [ 0.03566222,  0.03566222,  0.03566222],
         [ 1.1800017 ,  1.1800017 ,  1.1800017 ]],

        [[ 0.21102734,  0.21102734,  0.21102734],
         [ 0.42117536,  0.42117536,  0.42117536],
         [ 0.93851733,  0.93851733,  0.93851733],
         ...,
         [-1.3705354 , -1.3705354 , -1.3705354 ],
         [ 0.03566222,  0.03566222,  0.03566222],
         [ 1.1800017 ,  1.1800017 ,  1.1800017 ]],

        [[ 0.21102734,  0.21102734,  0.21102734],
         [ 0.42117536,  0.42117536,  0.42117536],
         [ 0.93851733,  0.93851733,  0.93851733],
         ...,
         [-1.3705354 , -1.3705354 , -1.3705354 ],
         [ 0.03566222,  0.03566222,  0.03566222],
         [ 1.1800017 ,  1.1800017 ,  1.1800017 ]

In [94]:
A = tf.random.normal([32,2])
# 不符合 Broadcasting 条件,不满足普适性
try: 
    tf.broadcast_to(A, [2,32,32,4])
except Exception as e:
    print(e)

Incompatible shapes: [32,2] vs. [2,32,32,4] [Op:BroadcastTo]


## 数学运算

### 加、减、乘、除运算

In [95]:
a = tf.range(5)
b = tf.constant(2)
# 整除运算
a//b 

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2])>

In [96]:
# 余除运算
a%b 

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0])>

### 乘方运算

In [97]:
x = tf.range(4)
# 乘方运算
tf.pow(x,3) 

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27])>

In [98]:
# 乘方运算符
x**2 

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9])>

In [99]:
x=tf.constant([1.,4.,9.])
# 平方根
x**(0.5) 

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [100]:
x = tf.range(5)
# 转换为浮点数
x = tf.cast(x, dtype=tf.float32) 
# 平方
x = tf.square(x) 
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16.], dtype=float32)>

In [101]:
# 平方根
tf.sqrt(x) 

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.        , 0.99999994, 1.9999999 , 2.9999998 , 4.        ],
      dtype=float32)>

### 指数和对数运算

In [102]:
x = tf.constant([1.,2.,3.])
# 指数运算
2**x 

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 8.], dtype=float32)>

In [103]:
# 自然指数运算
tf.exp(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7182817>

In [104]:
x = tf.exp(3.)
print(x)
# 对数运算
tf.math.log(x)

tf.Tensor(20.085537, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [105]:
x = tf.constant([1.,2.])
x = 10**x
# 换底公式
tf.math.log(x)/tf.math.log(10.) 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

### 矩阵相乘运算

In [106]:
a = tf.random.normal([4,3,28,32])
b = tf.random.normal([4,3,32,2])
# 批量形式的矩阵相乘
a@b

<tf.Tensor: shape=(4, 3, 28, 2), dtype=float32, numpy=
array([[[[ 1.35584879e+00, -1.09849815e+01],
         [-7.79025078e+00,  8.11223412e+00],
         [ 5.57515526e+00, -9.70366895e-01],
         [-5.47276688e+00,  1.06806812e+01],
         [-1.00901155e+01,  5.92649937e+00],
         [-3.16838503e+00,  4.00045204e+00],
         [-5.13781691e+00,  1.00689220e+01],
         [ 9.98535728e+00,  3.51211214e+00],
         [ 1.85937691e+00,  7.37776041e-01],
         [ 7.32646608e+00, -1.61254883e-01],
         [-8.78988743e+00, -8.43520260e+00],
         [ 1.11892252e+01,  3.59739423e-01],
         [-4.16237307e+00,  5.60024023e+00],
         [-1.19402957e+00,  2.94026089e+00],
         [-8.40427208e+00,  6.47729254e+00],
         [ 1.77078247e-02, -4.72327805e+00],
         [ 1.32010937e+01, -1.03036423e+01],
         [ 1.23897009e+01,  2.39869547e+00],
         [ 5.83752537e+00,  1.31873965e+00],
         [ 6.18176365e+00, -1.16569781e+00],
         [-5.91183758e+00, -4.66259956e+00],


In [107]:
a = tf.random.normal([4,28,32])
b = tf.random.normal([32,16])
# 先自动扩展，再矩阵相乘
tf.matmul(a,b)

<tf.Tensor: shape=(4, 28, 16), dtype=float32, numpy=
array([[[-4.66294098e+00, -3.99887967e+00, -5.58816624e+00, ...,
          8.14061928e+00,  9.33127403e+00,  1.25892305e+00],
        [ 2.71739483e+00, -5.62808228e+00, -1.10043058e+01, ...,
         -4.29183054e+00,  5.99561739e+00, -2.75970459e-01],
        [ 4.61309528e+00, -1.67703724e+00, -2.60978937e+00, ...,
         -5.04190779e+00, -2.79975247e+00,  4.59172773e+00],
        ...,
        [ 3.78472090e+00,  2.67759323e+00, -4.29436064e+00, ...,
         -3.08323646e+00, -1.00384176e-01, -2.16407442e+00],
        [ 5.96815205e+00, -3.55449605e+00,  2.32704401e+00, ...,
         -2.82810426e+00, -8.87331665e-01, -7.81965971e+00],
        [ 1.50592601e+00, -3.94204950e+00,  1.27084255e-02, ...,
         -1.88348079e+00, -1.00361176e+01,  1.36601343e+01]],

       [[-1.42126579e+01,  2.24714828e+00,  1.83943450e-01, ...,
          4.98054457e+00, -3.64691401e+00,  4.99209261e+00],
        [ 8.93015802e-01,  1.16011059e+00,  9.8173