In [1]:
import tensorflow as tf

$dropout(x_i)=\begin{cases}0, & if ~ x_i ~ is ~ dropped  \\\frac{x_i}{1-drop\_rate}, & if ~ x_i ~ is ~  not ~ dropped\end{cases}$

In [2]:
import numpy as np

def dropout(x, drop_rate):
    if drop_rate < 0. or drop_rate >= 1: 
        raise ValueError('Dropout rate must be in interval [0, 1).')
    retain_rate = 1. - drop_rate
    random_tensor = np.random.binomial(n=1, p=retain_rate, size=x.shape) 
    #A vector of 0, 1 distribution is about to be generated, 0 means that this neuron is masked
    #eg. Toss {n} coin at a time, the probability of heads is {p}, do {x.shape} times experiments, find {the number of coins} that land heads in each test
    print(random_tensor)
    x *= random_tensor
    print(x)
    x /= retain_rate
    return x

x=np.asarray([1,2,3,4,5,6,7,8,9,10],dtype=np.float32)
dropout(x,0.4)

[0 1 1 0 1 1 1 0 1 1]
[ 0.  2.  3.  0.  5.  6.  7.  0.  9. 10.]


array([ 0.       ,  3.3333333,  5.       ,  0.       ,  8.333333 ,
       10.       , 11.666666 ,  0.       , 14.999999 , 16.666666 ],
      dtype=float32)

In [3]:
tf.random.set_seed(0)
x = tf.cast([1,2,3,4,5,6,7,8,9,10],dtype=tf.float32)
tf.nn.dropout(x, rate = 0.4, noise_shape=[1,10], seed=1).numpy()

array([[ 1.6666666,  0.       ,  0.       ,  6.6666665,  8.333333 ,
        10.       , 11.666666 , 13.333333 , 15.       , 16.666666 ]],
      dtype=float32)